language: c

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ../ -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $CXX)
  
script:
- make
